name: rumacao_front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  shared_preferences: ^2.5.1
  http:
  path_provider: ^2.1.5


dependency_overrides:
  archive: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/mascote/neutral/
    - assets/images/mascote/partially_agree/
    - assets/images/mascote/partially_disagree/
    - assets/images/mascote/totally_agree/
    - assets/images/mascote/totally_disagree/
    - assets/images/mascote/results/

  fonts:
    - family: Dynamic Schematic
      fonts:
        - asset: assets/fonts/DynamicSchematic-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf